import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { useAuth } from '../context/AuthContext';
import { filterLocations, loadCargo, loadLocations, rankCargo, type CargoDirectoryItem, type LocationDirectoryItem } from '../features/calculator/directoryData';

type Props = { label: string; value: string; selectedId: string | null; endpoint: string; placeholder: string; required?: boolean; error?: string; kind?: 'location' | 'cargo'; onChange: (text: string, id: string | null) => void };
type Item = LocationDirectoryItem | CargoDirectoryItem;

export function DirectoryAutocomplete({ label, value, selectedId, endpoint, placeholder, required, error, kind = endpoint.includes('/cargo') ? 'cargo' : 'location', onChange }: Props) {
  const { apiFetch } = useAuth(); const [items, setItems] = useState<Item[]>([]); const [open, setOpen] = useState(false); const [highlight, setHighlight] = useState(-1); const [loading, setLoading] = useState(false); const [loadError, setLoadError] = useState(false); const rootRef = useRef<HTMLDivElement>(null); const dropdownRef = useRef<HTMLDivElement>(null);
  async function ensureLoaded(query = value) { setLoading(true); setLoadError(false); try { const all = kind === 'cargo' ? await loadCargo(apiFetch) : await loadLocations(apiFetch); const next = kind === 'cargo' ? rankCargo(all, query) : filterLocations(all, query); setItems(next); setHighlight(next.length ? 0 : -1); } catch { setItems([]); setLoadError(true); } finally { setLoading(false); } }
  useEffect(() => { if (!value) { setOpen(false); setHighlight(-1); return; } const timer = window.setTimeout(() => { void ensureLoaded(value).then(() => setOpen(true)); }, 120); return () => window.clearTimeout(timer); }, [apiFetch, kind, value]);
  useEffect(() => { const close = (event: MouseEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  useEffect(() => { if (highlight < 0 || !dropdownRef.current) return; const option = dropdownRef.current.children[highlight] as HTMLElement | undefined; if (!option) return; const top = option.offsetTop; const bottom = top + option.offsetHeight; if (top < dropdownRef.current.scrollTop) dropdownRef.current.scrollTop = top; if (bottom > dropdownRef.current.scrollTop + dropdownRef.current.clientHeight) dropdownRef.current.scrollTop = bottom - dropdownRef.current.clientHeight; }, [highlight]);
  function choose(item: Item) { onChange(item.label, item.id); setOpen(false); setHighlight(-1); }
  function onKeyDown(event: KeyboardEvent<HTMLInputElement>) { if (event.key === 'Escape') { setOpen(false); setHighlight(-1); return; } if (event.key === 'ArrowDown') { event.preventDefault(); setOpen(true); setHighlight((current) => items.length ? (current + 1) % items.length : -1); } if (event.key === 'ArrowUp') { event.preventDefault(); setOpen(true); setHighlight((current) => items.length ? (current <= 0 ? items.length - 1 : current - 1) : -1); } if (event.key === 'Enter' && open && highlight >= 0 && items[highlight]) { event.preventDefault(); choose(items[highlight]); } }
  const canOpenEmpty = kind === 'location';
  return <label className="directory-autocomplete-label">{label}{required && <span className="required">*</span>}<div className="directory-autocomplete" ref={rootRef}><input value={value} required={required} aria-invalid={Boolean(error || (value && !selectedId))} placeholder={placeholder} autoComplete="off" onFocus={() => { if (canOpenEmpty || value) { setOpen(true); void ensureLoaded(); } }} onKeyDown={onKeyDown} onChange={(event) => onChange(event.target.value, null)} />{open && <div className="directory-autocomplete-dropdown" role="listbox" ref={dropdownRef}>{loading && <div className="directory-autocomplete-state">Загрузка...</div>}{!loading && !loadError && items.map((item, index) => <button type="button" role="option" aria-selected={index === highlight} className={index === highlight ? 'is-active' : ''} key={item.id} onMouseDown={(event) => { event.preventDefault(); choose(item); }}>{item.label}</button>)}{!loading && loadError && <div className="directory-autocomplete-state is-error">Не удалось загрузить справочник</div>}{!loading && !loadError && items.length === 0 && <div className="directory-autocomplete-state">Ничего не найдено</div>}</div>}</div>{error && <span className="calculator-error">{error}</span>}</label>;
}
