import type { CalculationQuote } from '../types';

export function RouteStages({ quote }: { quote: CalculationQuote }) { return <section className="result-section"><div className="result-heading"><h2>Маршрут и этапы</h2><button className="text-button" type="button">+ Добавить этап</button></div><div className="stage-list">{quote.routeStages.map((stage) => <article className="stage-card" key={stage.number}><span className="stage-number">{stage.number}</span><div><strong>{stage.mode}</strong><b>{stage.title}</b><small>{stage.details}</small></div></article>)}</div></section>; }

export function AdditionalServices({ quote }: { quote: CalculationQuote }) { return <section className="result-section"><h2>Дополнительные услуги</h2><div className="service-summary-list">{quote.additionalServices.map((service) => <div className={service.active ? 'service-summary is-active' : 'service-summary'} key={service.name}><span>{service.active ? '✓' : '○'}</span>{service.name}<em>{service.active ? 'активна' : 'не выбрана'}</em></div>)}</div></section>; }

export function CalculationExplanation({ quote }: { quote: CalculationQuote }) { return <section className="result-section explanation"><div className="result-heading"><h2>Как рассчитано</h2><small>для проверки</small></div><strong>{quote.explanation.distance[0]}</strong>{quote.explanation.distance.slice(1).map((line) => <span key={line}>{line}</span>)}<strong>{quote.explanation.weight[0]}</strong>{quote.explanation.weight.slice(1).map((line) => <span key={line}>{line}</span>)}{quote.explanation.base.map((line) => <span key={line}>{line}</span>)}</section>; }

export function CalculationBreakdown({ quote }: { quote: CalculationQuote }) { return <section className="result-section breakdown"><div className="result-heading"><h2>Итог расчёта</h2></div>{quote.breakdown.map((line, index) => <div className={line.emphasis ? 'breakdown-line emphasis' : 'breakdown-line'} key={`${line.label}-${index}`}><span>{line.label}</span><strong>{line.value}</strong></div>)}<button className="pdf-button" type="button" onClick={() => undefined}>Сохранить расчёт в PDF</button></section>; }
