import type { ReactNode } from 'react';
import type { CalculationPdfData } from './types';

function money(value: number | null | undefined) { return value === null || value === undefined ? '—' : new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(Math.ceil(value)) + ' ₽'; }
function weight(value: string) { const number = Number(value.replace(/\s/g, '')); return Number.isFinite(number) ? new Intl.NumberFormat('ru-RU').format(number) + ' кг' : value; }
function days(value: number) { const m10 = value % 10; const m100 = value % 100; const word = m10 === 1 && m100 !== 11 ? 'день' : m10 >= 2 && m10 <= 4 && (m100 < 10 || m100 >= 20) ? 'дня' : 'дней'; return `${value} ${word}`; }
function city(value: string) { return value.split(',')[0]?.trim() || value; }
function Logo() { return <div className="calculation-pdf-logo"><strong>НОВИК</strong><small>логистическая группа</small></div>; }
function Card({ title, subtitle, children, className = '' }: { title: string; subtitle?: string; children: ReactNode; className?: string }) { return <section className={`calculation-pdf-card ${className}`}><h2>{title}</h2>{subtitle && <p className="calculation-pdf-subtitle">{subtitle}</p>}{children}</section>; }
function Header({ data, second = false }: { data: CalculationPdfData; second?: boolean }) { return <header className="calculation-pdf-header"><Logo /><div className="calculation-pdf-header-meta">{!second && <strong>РАСЧЁТ ТАРИФА</strong>}<span>Сделка № {data.dealId || '—'}</span><span>Тариф от {data.tariffDate}</span></div></header>; }
function Footer({ page }: { page: number }) { return <footer className="calculation-pdf-footer"><span>{page === 1 ? 'Расчёт носит информационный характер. Итоговые условия фиксируются в коммерческом предложении.' : 'ГК «Новик» • novikgroup.ru'}</span><span>{page} / 2</span></footer>; }
function Field({ label, value }: { label: string; value: string }) { return <div className="calculation-pdf-field"><span>{label}</span><strong>{value || '—'}</strong></div>; }

export function CalculationPdfPageOne({ data }: { data: CalculationPdfData }) {
  const quote = data.quote;
  const discount = data.baseDoorToDoor && data.baseDoorToDoor > 0 ? ((data.baseDoorToDoor - data.saleRate) / data.baseDoorToDoor) * 100 : 0;
  return <div className="calculation-pdf-page"><Header data={data} /><Card title={`${city(data.origin)} → ${city(data.destination)}`} className="calculation-pdf-hero"><p className="calculation-pdf-route-meta">Мультимодальная перевозка • {data.container || '—'} • {data.owner || '—'} • {weight(data.weightKg)}</p><strong className="calculation-pdf-sale"><span>Ставка продажи</span>{money(data.saleRate)}</strong><div className="calculation-pdf-hero-details"><Field label="Клиент" value={data.counterpartyName} /><Field label="Груз" value={data.cargo} /></div></Card><Card title="Параметры тарифа" subtitle="Условия перевозки и расчёта" className="calculation-pdf-params"><div><Field label="Отправление" value={data.origin} /><Field label="Назначение" value={data.destination} /><Field label="Контейнер" value={`${data.container} • ${data.category}`} /></div><div><Field label="Вес" value={weight(data.weightKg)} /><Field label="Владелец контейнера" value={data.owner === 'COC' ? 'NOVIK COC' : 'SOC'} /><Field label="Отсрочка платежа" value={days(data.paymentDelayDays)} /></div></Card><Card title="Коммерческая ставка" subtitle="Ключевые финансовые показатели расчёта" className="calculation-pdf-commercial"><div className="calculation-pdf-kpis calculation-pdf-kpis-top"><Field label="Ставка продажи" value={money(data.saleRate)} /><Field label="Базовый тариф дверь/дверь" value={money(data.baseDoorToDoor)} /><Field label="Скидка" value={`${Math.ceil(discount * 10) / 10}`.replace('.', ',') + ' %'} /></div><div className="calculation-pdf-divider" /><div className="calculation-pdf-kpis"><Field label="Эксп. маржа" value={quote.commercial.forwardingMargin} /><Field label="Эксп. маржа, %" value={quote.commercial.forwardingMarginPercent} /><Field label="Маржа сервисов Новик" value={quote.commercial.servicesMargin} /><Field label="Итого маржа" value={quote.commercial.totalMargin} /><Field label="Итого маржа, %" value={quote.commercial.totalMarginPercent} /></div></Card><Card title="Маршрут и этапы" subtitle="Расчёт по действующим тарифам и нормативам" className="calculation-pdf-stages">{quote.routeStages.map((stage) => <div className="calculation-pdf-stage" key={stage.number}><b>{stage.number}</b><div><strong>{stage.title}</strong><span>{stage.details}</span></div><em>{stage.amount}</em></div>)}</Card><Footer page={1} /></div>;
}

function Breakdown({ data }: { data: CalculationPdfData }) { const lines = data.quote.breakdown.filter((line) => line.label !== 'Ставка продажи'); return <div className="calculation-pdf-breakdown-lines">{lines.map((line, index) => { const previous = lines[index - 1]?.label; const dividerBefore = line.label === 'Прочие расходы' || line.label === 'Ставка продажи' || (line.label === 'Маржа базового тарифа LI-LO' && previous === 'Дополнительные услуги'); return <div className={`calculation-pdf-breakdown-line ${line.emphasis ? 'is-emphasis' : ''} ${dividerBefore ? 'is-divider-before' : ''}`} key={`${line.label}-${index}`}><span>{line.label}</span><strong>{line.value}</strong></div>; })}<div className="calculation-pdf-breakdown-line is-divider-before is-emphasis"><span>Ставка продажи</span><strong>{money(data.saleRate)}</strong></div></div>; }
function Services({ data }: { data: CalculationPdfData }) { return <Card title="Дополнительные услуги" subtitle="Выбранные опции текущего расчёта" className="calculation-pdf-services"><div className="calculation-pdf-chips">{data.quote.additionalServices.map((service) => <span className={service.active ? 'is-active' : ''} key={service.name}><i />{service.name}{service.active && service.amountValue ? ` • ${money(service.amountValue)}` : ''}</span>)}</div></Card>; }
function Approval() { return <Card title="Согласование" subtitle="Подписи ответственных лиц" className="calculation-pdf-approval"><div><strong>Руководитель отдела продаж</strong><span>Антропов А.Ю.</span><i /><small>подпись</small><em>/ Антропов А.Ю. /</em></div><div><strong>Директор по логистике и развитию</strong><span>Фоминский В.В.</span><i /><small>подпись</small><em>/ Фоминский В.В. /</em></div></Card>; }
export function CalculationPdfPageTwo({ data }: { data: CalculationPdfData }) { return <div className="calculation-pdf-page"><Header data={data} second /><Card title="Итог расчёта" subtitle="Детализация составляющих тарифа" className="calculation-pdf-breakdown"><Breakdown data={data} /></Card><Services data={data} /><Approval /><Footer page={2} /></div>; }

export function CalculationPdfDocument({ data }: { data: CalculationPdfData }) { return <div className="calculation-pdf"><CalculationPdfPageOne data={data} /><CalculationPdfPageTwo data={data} /></div>; }
